name: Coverage

on:
  push:
    branches:
      - master

jobs:
  sync-and-run:
    name: Run and Publish Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Check out gh-pages
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
        
      - name: Merge master -> gh-pages
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: master
          target_branch: gh-pages
          github_token: ${{ github.token }}
        
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install

      - name: Test Action
        run: yarn coverage

      - name: Publish updated coverage
        uses: EndBug/add-and-commit@v5
        with:
          add: '-A'
          branch: gh-pages
          message: 'Update coverage'
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}